project:
  type: book
  output-dir: docs
lang: es

book:
  title: "Estadística. Preguntas frecuentes"
  subtitle: "Para estudiantes, curiosos y público en general"
  author: "Roberto Behar, Pere Grima"
  date: today
  date-format: medium
  cover-image: cover.png
  sidebar:
      collapse-level: 1
  site-url: https://peregrima.github.io/Estadistica_FAQ/
  
  chapters:
    - index.qmd
    - Lista.qmd
    
    - part: "Estadística. Lo que es y lo que no es"
      chapters: 
        - 0101_Estadistica_Matematicas.qmd
        - 0102_Probabilidad_Estadistica.qmd
        - 0103_Que_es_Estadistica.qmd
        - 0104_DataScience.qmd
    
    - part: Estadística descriptiva
      chapters: 
        - 0201_Mediana.qmd
        - 0202_Media_geometrica.qmd
        - 0203_Variabilidad.qmd
        - 0204_Varianza_cuadrado.qmd
        - 0205_Dividir_n_1.qmd
        - 0206_Desviacion_tipica.qmd
        - 0207_Cuartiles_correcta.qmd
        - 0208_Anomalias_boxplot.qmd
        - 0209_Valores_atipicos.qmd
        - 0210_Curtosis.qmd
        - 0211_Graficos_usar.qmd
        - 0212_Graficos_NO_usar.qmd
        - 0213_Software.qmd

    - part: Distribuciones de probabilidad
      chapters: 
        - 0301_Frecuencia_densidad.qmd
        - 0302_Que_Distribucion.qmd
        - 0303_Media_var_aleatoria.qmd
        - 0304_formula_Normal.qmd
        - 0305_Solo_N01.qmd
        - 0306_Estatura_cero.qmd
        - 0307_Contrario_Normal.qmd
        - 0308_Formula_Poisson.qmd
        - 0309_Varianza_Chi_cuadrado.qmd
        - 0310_Sumark_Multiplicark.qmd
        
    - part: Muestreo y Estimación
      chapters: 
        - 0401_Creemos_muestra.qmd
        - 0402_Intervalo_confianza.qmd
        - 0403_Factor_correccion.qmd
        - 0404_Elementos_muestra.qmd
        - 0405_Muestra_poblacion.qmd
        - 0406_Tipo_muestreo.qmd
        - 0407_Aleatoria_representativa.qmd
        - 0408_Acertar_sondeos.qmd
        - 0409_Maximoverosimil.qmd

    - part: Contraste de hipótesis
      chapters: 
        - 0501_Que_es.qmd
        - 0502_Controvertido.qmd
        - 0503_Que_alternativa.qmd
        - 0504_No_rechazo.qmd
        - 0505_Lado_cola.qmd
        - 0506_p_valor.qmd
        - 0507_Tipos_error.qmd
        - 0508_Significativa.qmd
        - 0509_Por2_cola_F.qmd
        
    - part: Diseño de experimentos
      chapters: 
        - 0601_FisicaQuimica.qmd
        - 0602_tStudent.qmd
        - 0603_ANOVA_Medias.qmd
        - 0604_No_UnaaUna.qmd
        - 0605_Efecto_separado.qmd
        - 0606_Ecuacion.qmd
        - 0607_Bloqueo.qmd
        - 0608_Interacciones.qmd
        - 0609_Aleatorizar.qmd

    - part: Correlación y regresión
      chapters: 
        - 0701_Formula_covarianza.qmd
        - 0702_Coef_correlacion.qmd
        - 0703_Valores_criticos.qmd
        - 0704_Tablas_CoefCorre.qmd
        - 0705_Minimos_cuadrados.qmd
        - 0706_Coef_VariablesAleatorias.qmd
        - 0707_R2.qmd
        - 0708_Recta_Origen_R2.qmd
        - 0709_R2_ajustado.qmd
        - 0710_Variables_cualitativas.qmd
        - 0711_Varibles_Modelo.qmd
        
    - part: Miscelánea
      chapters: 
        - 0801_Logaritmo.qmd
        - 0802_TCL.qmd
        - 0803_Grados_libertad.qmd
        - 0804_Loteria.qmd
        - 0805_Rojo_Negro.qmd
        - 0806_Como_se_dice.qmd

# Referencias
# biblio-title: "Referencias"
# link-citations: true
# link-bibliography: true
# cite-method: citeproc         # Solo PDF
# biblio-style: 'authoryear'    # Solo PDF
# citations-hover: true         # Solo HTML
# bibliography: references.bib 

# Fuentes ----------------------------
mainfont: Calibri
monofont: Verdana
mathfont: CambriaMath
fontfamily: baskervald    # -> Solo en PDF
fontsize: 13pt
# systemfonts::system_fonts(): Lista de fuentes disponibles en el ordenador.


format:
  html:
    theme: cosmo
    code-fold: true
    css: styles.css
    header-includes:
      <script src="https://kit.fontawesome.com/98a945d90a.js" crossorigin="anonymous"></script>

editor: visual

