project:
  type: book
  output-dir: docs
lang: es

book:
  title: "Estadística. Preguntas frecuentes"
  subtitle: "Para estudiantes, curiosos y público en general"
  author: "Roberto Behar, Pere Grima"
  date: today
  date-format: medium
  cover-image: cover.png
  site-url: https://peregrima.github.io/Estadistica_FAQ/
  
  chapters:
    - index.qmd
    
    - part: Estadística. Lo que es y lo que no es
      chapters: 
        - 0101_Estadistica_Matematicas.qmd
        - 0102_Probabilidad_Estadistica.qmd
        - 0103_Que_es_Estadistica.qmd
        - 0104_DataScience.qmd
    
    - part: 02_Estadistica_Descriptiva.qmd
      chapters: 
        - 0201_Mediana.qmd
        - 0202_Media_geometrica.qmd

# Referencias
# biblio-title: "Referencias"
# link-citations: true
# link-bibliography: true
# cite-method: citeproc         # Solo PDF
# biblio-style: 'authoryear'    # Solo PDF
# citations-hover: true         # Solo HTML
# bibliography: references.bib 

# Fuentes ----------------------------
mainfont: Calibri
monofont: Verdana
mathfont: CambriaMath
fontfamily: baskervald    # -> Solo en PDF
fontsize: 14pt
# systemfonts::system_fonts(): Lista de fuentes disponibles en el ordenador.


format:
  html:
    theme: cosmo
    code-fold: true
    css: styles.css
    header-includes:
      <script src="https://kit.fontawesome.com/98a945d90a.js" crossorigin="anonymous"></script>

editor: visual

